name: Kylie Ying
# permalink: /:title/
# baseurl: https://kylieying.com
# baseurl: ""
permalink: /blog/:title

# seo tag
plugins:
  - jekyll-seo-tag

# Google Analytics
google_analytics: G-TEEDE1GB8S
